=== rasitoo/Clase/1dam/LM/XML/ACT11 ventaseditorial.dtd
<!ELEMENT informe (Cabecera, Datos)>
<!ELEMENT Cabecera (Titulo?,Desc?,Fecha)>
<!ELEMENT Titulo (#PCDATA)>
<!ELEMENT Desc (#PCDATA)>
<!ELEMENT Fecha EMPTY>
<!ATTLIST Fecha
    Day CDATA #REQUIRED
    Month CDATA #REQUIRED
    Year CDATA #REQUIRED>
<!ELEMENT Datos (Region, Trimestre+)>
<!ELEMENT Region (#PCDATA)>
<!ELEMENT Trimestre  (Ventas)>
<!ATTLIST Trimestre 
    numero (1|2|3|4) #REQUIRED>
<!ATTLIST Ventas LibrosVendidos CDATA "NO_INFO">
<!ELEMENT Ventas (#PCDATA)>

=== rasitoo/Clase/1dam/LM/XML/ACT11 ventaseditorial.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE informe SYSTEM "ACT11 ventaseditorial.dtd">
<informe>
    <Cabecera>
        <Desc>Esto es un informe</Desc>
        <Fecha Day="24" Month="2" Year="2243" />
    </Cabecera>
    <Datos>
        <Region>Norte</Region>
        <Trimestre numero="1">
            <Ventas></Ventas>
        </Trimestre>
    </Datos>
</informe>
